### ISSUE TITLE
Json.tla in place of python parser?

### ISSUE THREAD

**Issue by lemmy** [dgpv/bip32_template_parse_tplaplus_spec#1]
The [TLA+ Community Modules](https://github.com/tlaplus/CommunityModules) have a [Json](https://github.com/tlaplus/CommunityModules/blob/master/modules/Json.tla) module to convert TLA+ to Json, which might make the Python based parsing obsolete.

**Comment by dgpv** [comment]
The main use of the python script is not to convert, but to transform (could't use 0x7FFFFFFF in the model, had to use 255 and convert) and filter (not all generated data is useful, and filtering it in TLA is cumbersome or impossible)

The conversion is simple and straightforward (for the type of data this particular model generates), so I decided not to involve additional modules, which would be external dependencies, that would require manual installation for those who want to try to run the checking

**Comment by dgpv** [comment]
Closing this. For more complex generated data structures using the Json community module makes sense, but for this, the cost of extra dependency is not justified, in my opinion.
