### ISSUE TITLE
Evaluate TLA+ expressions on the command-line

### ISSUE THREAD

**Issue by lemmy** [dgpv/bip32_template_parse_tplaplus_spec#2]
The readme claims that one cannot evaluate TLA+ expressions on the command-line.  The recent 1.7.0 release added [support for trace expression evaluation on the command-line](https://github.com/tlaplus/tlaplus/issues/393).

[![Alt text](https://img.youtube.com/vi/pTN3nHvSm84/0.jpg)](https://youtu.be/pTN3nHvSm84)

**Comment by dgpv** [comment]
Cool, I didn't know. Fixed the readme to reference version 1.7.0 and the video in https://github.com/dgpv/bip32_template_parse_tplaplus_spec/commit/83d91277447de51b9d610f6a8def3a0a03c7b5de
